mappings:
  apollo.bk.v1.TransactionKey: "fleet/bk"
  apollo.bk.v1.Transaction: "fleet/bk"
  apollo.bk.v1.TransactionEnvelope: "fleet/bk"
  apollo.bk.v1.Event: "fleet/bk"
  apollo.bk.v1.SodCheckpointEvent: "fleet/bk"
  apollo.bkload.v1alpha1.MarkersComplete: "fleet/bkload"
  apollo.secfin.v1beta3.RepoEvent: "fleet/secfin"
  apollo.secfin.v1.InternalEvent: "fleet/secfin"
  apollo.secfin.v1.Event: "fleet/secfin"
  apollo.secfin.v2.Event: "fleet/secfin"
  apollo.secfin.v2.InternalEvent: "fleet/secfin"
  apollo.obligations.v1.Event: "fleet/obligations"
  apollo.obligations.v1.InternalEvent: "fleet/obligations"
  phoenix.basis.v1.Eodeconomic: "fleet/basis"
  phoenix.basis.v1.Eodposition: "fleet/basis"
  pmaggregate.v1alpha1.PmAggregatedResultPayload: "fleet/pm-aggregator"
  pmaggregate.v1alpha1.PmAggregatedResultKeyPayload: "fleet/pm-aggregator"
  mmresults.v1alpha1.MmResultKeyPayload: "fleet/pm-aggregator"
  mmresults.v1alpha1.MmResultPayload: "fleet/pm-aggregator"
  mmresults.v1alpha1.MmResultPayloadV2: "fleet/pm-aggregator"
  riskmeasures.v1alpha1.InstrumentPriceKeyPayload: "fleet/risk-measures"
  riskmeasures.v1alpha1.InstrumentPricePayload: "fleet/risk-measures"